name: eqpodcast
favicon: null
layout_spectrum: 0.43550894339568913
typography_spectrum: 0.24029138777405024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.37095429794862866
  lightness: 0.13526812405325472
  saturation: 0.7299863402731717
  rhythmicContrast: 0.5850533174816519
purpose: []
